// <auto-generated />
using System;
using BEARLINGO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BEARLINGO.Migrations
{
    [DbContext(typeof(BearlingoContext))]
    [Migration("20231105085925_editTable")]
    partial class editTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BEARLINGO.Models.Audio", b =>
                {
                    b.Property<int>("Idaudio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDAudio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idaudio"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IddeThi")
                        .HasColumnType("int")
                        .HasColumnName("IDDeThi");

                    b.Property<string>("TenFile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idaudio")
                        .HasName("PK__Audio__59DA2EDA1304EF34");

                    b.HasIndex("IddeThi");

                    b.ToTable("Audio", (string)null);
                });

            modelBuilder.Entity("BEARLINGO.Models.BaiLam", b =>
                {
                    b.Property<int>("IdbaiLam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDBaiLam");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdbaiLam"));

                    b.Property<int?>("DiemL")
                        .HasColumnType("int");

                    b.Property<int?>("DiemR")
                        .HasColumnType("int");

                    b.Property<int>("IddeThi")
                        .HasColumnType("int")
                        .HasColumnName("IDDeThi");

                    b.Property<int>("IdnguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("IDNguoiDung");

                    b.Property<DateTime?>("NgayThi")
                        .HasColumnType("date");

                    b.Property<int?>("SoCauDungL")
                        .HasColumnType("int");

                    b.Property<int?>("SoCauDungR")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("ThoiGian")
                        .HasColumnType("time");

                    b.HasKey("IdbaiLam")
                        .HasName("PK__BaiLam__CD7D499CD318B22B");

                    b.HasIndex("IddeThi");

                    b.HasIndex("IdnguoiDung");

                    b.ToTable("BaiLam", (string)null);
                });

            modelBuilder.Entity("BEARLINGO.Models.Blog", b =>
                {
                    b.Property<int>("Idblog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDBlog");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idblog"));

                    b.Property<string>("Anh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Idqtv")
                        .HasColumnType("int")
                        .HasColumnName("IDQTV");

                    b.Property<string>("NoiDungBlog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idblog")
                        .HasName("PK__Blog__3CFB8BBEEAD003C4");

                    b.HasIndex("Idqtv");

                    b.ToTable("Blog", (string)null);
                });

            modelBuilder.Entity("BEARLINGO.Models.ChuDeNguPhap", b =>
                {
                    b.Property<int>("IdchuDeNguPhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDChuDeNguPhap");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdchuDeNguPhap"));

                    b.Property<int>("Idqtv")
                        .HasColumnType("int")
                        .HasColumnName("IDQTV");

                    b.Property<int?>("Stt")
                        .HasColumnType("int")
                        .HasColumnName("STT");

                    b.Property<string>("TenNguPhap")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdchuDeNguPhap")
                        .HasName("PK__ChuDeNgu__37E44C4947A089D0");

                    b.HasIndex("Idqtv");

                    b.ToTable("ChuDeNguPhap", (string)null);
                });

            modelBuilder.Entity("BEARLINGO.Models.ChuDeTuVung", b =>
                {
                    b.Property<int>("IdchuDeTuVung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDChuDeTuVung");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdchuDeTuVung"));

                    b.Property<string>("ChuDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Idqtv")
                        .HasColumnType("int")
                        .HasColumnName("IDQTV");

                    b.Property<int?>("Stt")
                        .HasColumnType("int")
                        .HasColumnName("STT");

                    b.HasKey("IdchuDeTuVung")
                        .HasName("PK__ChuDeTuV__15A303D8092F2D24");

                    b.HasIndex("Idqtv");

                    b.ToTable("ChuDeTuVung", (string)null);
                });

            modelBuilder.Entity("BEARLINGO.Models.DeThi", b =>
                {
                    b.Property<int>("IddeThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDDeThi");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IddeThi"));

                    b.Property<int>("Idets")
                        .HasColumnType("int")
                        .HasColumnName("IDETS");

                    b.Property<int>("Idqtv")
                        .HasColumnType("int")
                        .HasColumnName("IDQTV");

                    b.Property<string>("TenDeThi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("ThoiGian")
                        .HasColumnType("time");

                    b.HasKey("IddeThi")
                        .HasName("PK__DeThi__18DD254977388BB7");

                    b.HasIndex("Idets");

                    b.HasIndex("Idqtv");

                    b.ToTable("DeThi", (string)null);
                });

            modelBuilder.Entity("BEARLINGO.Models.Et", b =>
                {
                    b.Property<int>("Idets")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDETS");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idets"));

                    b.Property<int>("Idqtv")
                        .HasColumnType("int")
                        .HasColumnName("IDQTV");

                    b.Property<string>("TenEts")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TenETS");

                    b.HasKey("Idets")
                        .HasName("PK__ETS__9228B3476B54FBEC");

                    b.HasIndex("Idqtv");

                    b.ToTable("ETS", (string)null);
                });

            modelBuilder.Entity("BEARLINGO.Models.KetQuaL", b =>
                {
                    b.Property<int>("IdketQuaL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDKetQuaL");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdketQuaL"));

                    b.Property<string>("CorrectL")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DapAnNguoiDungL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdbaiLam")
                        .HasColumnType("int")
                        .HasColumnName("IDBaiLam");

                    b.Property<int>("Idlquestion")
                        .HasColumnType("int")
                        .HasColumnName("IDLQuestion");

                    b.HasKey("IdketQuaL")
                        .HasName("PK__KetQuaL__6D3D3866C1C2BAE9");

                    b.HasIndex("IdbaiLam");

                    b.HasIndex("Idlquestion");

                    b.ToTable("KetQuaL", (string)null);
                });

            modelBuilder.Entity("BEARLINGO.Models.KetQuaR", b =>
                {
                    b.Property<int>("IdketQuaR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDKetQuaR");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdketQuaR"));

                    b.Property<string>("CorrectR")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DapAnNguoiDungR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdbaiLam")
                        .HasColumnType("int")
                        .HasColumnName("IDBaiLam");

                    b.Property<int>("Idrquestion")
                        .HasColumnType("int")
                        .HasColumnName("IDRQuestion");

                    b.HasKey("IdketQuaR")
                        .HasName("PK__KetQuaR__6D3D385CE38CA5E4");

                    b.HasIndex("IdbaiLam");

                    b.HasIndex("Idrquestion");

                    b.ToTable("KetQuaR", (string)null);
                });

            modelBuilder.Entity("BEARLINGO.Models.Listening", b =>
                {
                    b.Property<int>("Idlquestion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDLQuestion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idlquestion"));

                    b.Property<string>("DapAn1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAn2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAn3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAn4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAnDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiaiThich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Idaudio")
                        .HasColumnType("int")
                        .HasColumnName("IDAudio");

                    b.Property<int>("IddeThi")
                        .HasColumnType("int")
                        .HasColumnName("IDDeThi");

                    b.Property<int>("IdphanLoaiL")
                        .HasColumnType("int")
                        .HasColumnName("IDPhanLoaiL");

                    b.Property<int>("Idpicture")
                        .HasColumnType("int")
                        .HasColumnName("IDPicture");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Stt")
                        .HasColumnType("int")
                        .HasColumnName("STT");

                    b.HasKey("Idlquestion")
                        .HasName("PK__Listenin__E1F3BA46FE01AB5F");

                    b.HasIndex("Idaudio");

                    b.HasIndex("IddeThi");

                    b.HasIndex("IdphanLoaiL");

                    b.HasIndex("Idpicture");

                    b.ToTable("Listening", (string)null);
                });

            modelBuilder.Entity("BEARLINGO.Models.NguPhap", b =>
                {
                    b.Property<int>("IdnguPhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDNguPhap");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdnguPhap"));

                    b.Property<string>("BoSung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CachDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CauTruc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdchuDeNguPhap")
                        .HasColumnType("int")
                        .HasColumnName("IDChuDeNguPhap");

                    b.Property<string>("LuuY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViDu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdnguPhap")
                        .HasName("PK__NguPhap__CA382F828A26A02F");

                    b.HasIndex("IdchuDeNguPhap");

                    b.ToTable("NguPhap", (string)null);
                });

            modelBuilder.Entity("BEARLINGO.Models.NguoiDung", b =>
                {
                    b.Property<int>("IdnguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDNguoiDung");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdnguoiDung"));

                    b.Property<string>("Gmail")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Sdt")
                        .HasColumnType("int")
                        .HasColumnName("SDT");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdnguoiDung")
                        .HasName("PK__NguoiDun__FCD7DB0965E4F7E8");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("BEARLINGO.Models.PhanLoaiL", b =>
                {
                    b.Property<int>("IdphanLoaiL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPhanLoaiL");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdphanLoaiL"));

                    b.Property<string>("Loai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenAudio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdphanLoaiL")
                        .HasName("PK__PhanLoai__C0851AC030D020D1");

                    b.ToTable("PhanLoaiL", (string)null);
                });

            modelBuilder.Entity("BEARLINGO.Models.PhanLoaiR", b =>
                {
                    b.Property<int>("IdphanLoaiR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPhanLoaiR");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdphanLoaiR"));

                    b.Property<string>("Loai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdphanLoaiR")
                        .HasName("PK__PhanLoai__C0851D3AEEDA15AE");

                    b.ToTable("PhanLoaiR", (string)null);
                });

            modelBuilder.Entity("BEARLINGO.Models.Picture", b =>
                {
                    b.Property<int>("Idpicture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPicture");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idpicture"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IddeThi")
                        .HasColumnType("int")
                        .HasColumnName("IDDeThi");

                    b.Property<string>("TenFile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idpicture")
                        .HasName("PK__Picture__C37C3FD19C5FF7AE");

                    b.HasIndex("IddeThi");

                    b.ToTable("Picture", (string)null);
                });

            modelBuilder.Entity("BEARLINGO.Models.Qtv", b =>
                {
                    b.Property<int>("Idqtv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDQTV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idqtv"));

                    b.Property<string>("Gmail")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Idqtv")
                        .HasName("PK__QTV__A74052336123A937");

                    b.ToTable("QTV", (string)null);
                });

            modelBuilder.Entity("BEARLINGO.Models.Reading", b =>
                {
                    b.Property<int>("Idrquestion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDRQuestion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idrquestion"));

                    b.Property<string>("DapAn1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAn2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAn3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAn4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAnDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiaiThich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IddeThi")
                        .HasColumnType("int")
                        .HasColumnName("IDDeThi");

                    b.Property<int>("IdphanLoaiR")
                        .HasColumnType("int")
                        .HasColumnName("IDPhanLoaiR");

                    b.Property<int>("Idpicture")
                        .HasColumnType("int")
                        .HasColumnName("IDPicture");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Stt")
                        .HasColumnType("int")
                        .HasColumnName("STT");

                    b.HasKey("Idrquestion")
                        .HasName("PK__Reading__2C13B396986FC12C");

                    b.HasIndex("IddeThi");

                    b.HasIndex("IdphanLoaiR");

                    b.HasIndex("Idpicture");

                    b.ToTable("Reading", (string)null);
                });

            modelBuilder.Entity("BEARLINGO.Models.Tip", b =>
                {
                    b.Property<int>("Idtips")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDTips");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idtips"));

                    b.Property<string>("Anh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Idqtv")
                        .HasColumnType("int")
                        .HasColumnName("IDQTV");

                    b.Property<string>("NoiDungTips")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idtips")
                        .HasName("PK__Tips__BEB088A2FD3C9164");

                    b.HasIndex("Idqtv");

                    b.ToTable("Tips");
                });

            modelBuilder.Entity("BEARLINGO.Models.TuVung", b =>
                {
                    b.Property<int>("IdtuVung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDTuVung");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdtuVung"));

                    b.Property<int>("IdchuDeTuVung")
                        .HasColumnType("int")
                        .HasColumnName("IDChuDeTuVung");

                    b.Property<string>("LoaiTu")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("char(255)")
                        .IsFixedLength();

                    b.Property<string>("NghiaTuVung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhatAm")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TuVung1")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("TuVung");

                    b.Property<string>("ViDuTuVung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdtuVung")
                        .HasName("PK__TuVung__3D5AF069BF66DF17");

                    b.HasIndex("IdchuDeTuVung");

                    b.ToTable("TuVung", (string)null);
                });

            modelBuilder.Entity("BEARLINGO.Models.Audio", b =>
                {
                    b.HasOne("BEARLINGO.Models.DeThi", "IddeThiNavigation")
                        .WithMany("Audios")
                        .HasForeignKey("IddeThi")
                        .IsRequired()
                        .HasConstraintName("FK__Audio__IDDeThi__45F365D3");

                    b.Navigation("IddeThiNavigation");
                });

            modelBuilder.Entity("BEARLINGO.Models.BaiLam", b =>
                {
                    b.HasOne("BEARLINGO.Models.DeThi", "IddeThiNavigation")
                        .WithMany("BaiLams")
                        .HasForeignKey("IddeThi")
                        .IsRequired()
                        .HasConstraintName("FK__BaiLam__IDDeThi__403A8C7D");

                    b.HasOne("BEARLINGO.Models.NguoiDung", "IdnguoiDungNavigation")
                        .WithMany("BaiLams")
                        .HasForeignKey("IdnguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK__BaiLam__IDNguoiD__412EB0B6");

                    b.Navigation("IddeThiNavigation");

                    b.Navigation("IdnguoiDungNavigation");
                });

            modelBuilder.Entity("BEARLINGO.Models.Blog", b =>
                {
                    b.HasOne("BEARLINGO.Models.Qtv", "IdqtvNavigation")
                        .WithMany("Blogs")
                        .HasForeignKey("Idqtv")
                        .IsRequired()
                        .HasConstraintName("FK__Blog__IDQTV__2E1BDC42");

                    b.Navigation("IdqtvNavigation");
                });

            modelBuilder.Entity("BEARLINGO.Models.ChuDeNguPhap", b =>
                {
                    b.HasOne("BEARLINGO.Models.Qtv", "IdqtvNavigation")
                        .WithMany("ChuDeNguPhaps")
                        .HasForeignKey("Idqtv")
                        .IsRequired()
                        .HasConstraintName("FK__ChuDeNguP__IDQTV__36B12243");

                    b.Navigation("IdqtvNavigation");
                });

            modelBuilder.Entity("BEARLINGO.Models.ChuDeTuVung", b =>
                {
                    b.HasOne("BEARLINGO.Models.Qtv", "IdqtvNavigation")
                        .WithMany("ChuDeTuVungs")
                        .HasForeignKey("Idqtv")
                        .IsRequired()
                        .HasConstraintName("FK__ChuDeTuVu__IDQTV__30F848ED");

                    b.Navigation("IdqtvNavigation");
                });

            modelBuilder.Entity("BEARLINGO.Models.DeThi", b =>
                {
                    b.HasOne("BEARLINGO.Models.Et", "IdetsNavigation")
                        .WithMany("DeThis")
                        .HasForeignKey("Idets")
                        .IsRequired()
                        .HasConstraintName("FK__DeThi__IDETS__3D5E1FD2");

                    b.HasOne("BEARLINGO.Models.Qtv", "IdqtvNavigation")
                        .WithMany("DeThis")
                        .HasForeignKey("Idqtv")
                        .IsRequired()
                        .HasConstraintName("FK__DeThi__IDQTV__3C69FB99");

                    b.Navigation("IdetsNavigation");

                    b.Navigation("IdqtvNavigation");
                });

            modelBuilder.Entity("BEARLINGO.Models.Et", b =>
                {
                    b.HasOne("BEARLINGO.Models.Qtv", "IdqtvNavigation")
                        .WithMany("Ets")
                        .HasForeignKey("Idqtv")
                        .IsRequired()
                        .HasConstraintName("FK__ETS__IDQTV__286302EC");

                    b.Navigation("IdqtvNavigation");
                });

            modelBuilder.Entity("BEARLINGO.Models.KetQuaL", b =>
                {
                    b.HasOne("BEARLINGO.Models.BaiLam", "IdbaiLamNavigation")
                        .WithMany("KetQuaLs")
                        .HasForeignKey("IdbaiLam")
                        .IsRequired()
                        .HasConstraintName("FK__KetQuaL__IDBaiLa__59063A47");

                    b.HasOne("BEARLINGO.Models.Listening", "IdlquestionNavigation")
                        .WithMany("KetQuaLs")
                        .HasForeignKey("Idlquestion")
                        .IsRequired()
                        .HasConstraintName("FK__KetQuaL__IDLQues__5812160E");

                    b.Navigation("IdbaiLamNavigation");

                    b.Navigation("IdlquestionNavigation");
                });

            modelBuilder.Entity("BEARLINGO.Models.KetQuaR", b =>
                {
                    b.HasOne("BEARLINGO.Models.BaiLam", "IdbaiLamNavigation")
                        .WithMany("KetQuaRs")
                        .HasForeignKey("IdbaiLam")
                        .IsRequired()
                        .HasConstraintName("FK__KetQuaR__IDBaiLa__5CD6CB2B");

                    b.HasOne("BEARLINGO.Models.Reading", "IdrquestionNavigation")
                        .WithMany("KetQuaRs")
                        .HasForeignKey("Idrquestion")
                        .IsRequired()
                        .HasConstraintName("FK__KetQuaR__IDRQues__5BE2A6F2");

                    b.Navigation("IdbaiLamNavigation");

                    b.Navigation("IdrquestionNavigation");
                });

            modelBuilder.Entity("BEARLINGO.Models.Listening", b =>
                {
                    b.HasOne("BEARLINGO.Models.Audio", "IdaudioNavigation")
                        .WithMany("Listenings")
                        .HasForeignKey("Idaudio")
                        .IsRequired()
                        .HasConstraintName("FK__Listening__IDAud__4D94879B");

                    b.HasOne("BEARLINGO.Models.DeThi", "IddeThiNavigation")
                        .WithMany("Listenings")
                        .HasForeignKey("IddeThi")
                        .IsRequired()
                        .HasConstraintName("FK__Listening__IDDeT__4BAC3F29");

                    b.HasOne("BEARLINGO.Models.PhanLoaiL", "IdphanLoaiLNavigation")
                        .WithMany("Listenings")
                        .HasForeignKey("IdphanLoaiL")
                        .IsRequired()
                        .HasConstraintName("FK__Listening__IDPha__4CA06362");

                    b.HasOne("BEARLINGO.Models.Picture", "IdpictureNavigation")
                        .WithMany("Listenings")
                        .HasForeignKey("Idpicture")
                        .IsRequired()
                        .HasConstraintName("FK__Listening__IDPic__4E88ABD4");

                    b.Navigation("IdaudioNavigation");

                    b.Navigation("IddeThiNavigation");

                    b.Navigation("IdphanLoaiLNavigation");

                    b.Navigation("IdpictureNavigation");
                });

            modelBuilder.Entity("BEARLINGO.Models.NguPhap", b =>
                {
                    b.HasOne("BEARLINGO.Models.ChuDeNguPhap", "IdchuDeNguPhapNavigation")
                        .WithMany("NguPhaps")
                        .HasForeignKey("IdchuDeNguPhap")
                        .IsRequired()
                        .HasConstraintName("FK__NguPhap__IDChuDe__398D8EEE");

                    b.Navigation("IdchuDeNguPhapNavigation");
                });

            modelBuilder.Entity("BEARLINGO.Models.Picture", b =>
                {
                    b.HasOne("BEARLINGO.Models.DeThi", "IddeThiNavigation")
                        .WithMany("Pictures")
                        .HasForeignKey("IddeThi")
                        .IsRequired()
                        .HasConstraintName("FK__Picture__IDDeThi__48CFD27E");

                    b.Navigation("IddeThiNavigation");
                });

            modelBuilder.Entity("BEARLINGO.Models.Reading", b =>
                {
                    b.HasOne("BEARLINGO.Models.DeThi", "IddeThiNavigation")
                        .WithMany("Readings")
                        .HasForeignKey("IddeThi")
                        .IsRequired()
                        .HasConstraintName("FK__Reading__IDDeThi__534D60F1");

                    b.HasOne("BEARLINGO.Models.PhanLoaiR", "IdphanLoaiRNavigation")
                        .WithMany("Readings")
                        .HasForeignKey("IdphanLoaiR")
                        .IsRequired()
                        .HasConstraintName("FK__Reading__IDPhanL__5441852A");

                    b.HasOne("BEARLINGO.Models.Picture", "IdpictureNavigation")
                        .WithMany("Readings")
                        .HasForeignKey("Idpicture")
                        .IsRequired()
                        .HasConstraintName("FK__Reading__IDPictu__5535A963");

                    b.Navigation("IddeThiNavigation");

                    b.Navigation("IdphanLoaiRNavigation");

                    b.Navigation("IdpictureNavigation");
                });

            modelBuilder.Entity("BEARLINGO.Models.Tip", b =>
                {
                    b.HasOne("BEARLINGO.Models.Qtv", "IdqtvNavigation")
                        .WithMany("Tips")
                        .HasForeignKey("Idqtv")
                        .IsRequired()
                        .HasConstraintName("FK__Tips__IDQTV__2B3F6F97");

                    b.Navigation("IdqtvNavigation");
                });

            modelBuilder.Entity("BEARLINGO.Models.TuVung", b =>
                {
                    b.HasOne("BEARLINGO.Models.ChuDeTuVung", "IdchuDeTuVungNavigation")
                        .WithMany("TuVungs")
                        .HasForeignKey("IdchuDeTuVung")
                        .IsRequired()
                        .HasConstraintName("FK__TuVung__IDChuDeT__33D4B598");

                    b.Navigation("IdchuDeTuVungNavigation");
                });

            modelBuilder.Entity("BEARLINGO.Models.Audio", b =>
                {
                    b.Navigation("Listenings");
                });

            modelBuilder.Entity("BEARLINGO.Models.BaiLam", b =>
                {
                    b.Navigation("KetQuaLs");

                    b.Navigation("KetQuaRs");
                });

            modelBuilder.Entity("BEARLINGO.Models.ChuDeNguPhap", b =>
                {
                    b.Navigation("NguPhaps");
                });

            modelBuilder.Entity("BEARLINGO.Models.ChuDeTuVung", b =>
                {
                    b.Navigation("TuVungs");
                });

            modelBuilder.Entity("BEARLINGO.Models.DeThi", b =>
                {
                    b.Navigation("Audios");

                    b.Navigation("BaiLams");

                    b.Navigation("Listenings");

                    b.Navigation("Pictures");

                    b.Navigation("Readings");
                });

            modelBuilder.Entity("BEARLINGO.Models.Et", b =>
                {
                    b.Navigation("DeThis");
                });

            modelBuilder.Entity("BEARLINGO.Models.Listening", b =>
                {
                    b.Navigation("KetQuaLs");
                });

            modelBuilder.Entity("BEARLINGO.Models.NguoiDung", b =>
                {
                    b.Navigation("BaiLams");
                });

            modelBuilder.Entity("BEARLINGO.Models.PhanLoaiL", b =>
                {
                    b.Navigation("Listenings");
                });

            modelBuilder.Entity("BEARLINGO.Models.PhanLoaiR", b =>
                {
                    b.Navigation("Readings");
                });

            modelBuilder.Entity("BEARLINGO.Models.Picture", b =>
                {
                    b.Navigation("Listenings");

                    b.Navigation("Readings");
                });

            modelBuilder.Entity("BEARLINGO.Models.Qtv", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("ChuDeNguPhaps");

                    b.Navigation("ChuDeTuVungs");

                    b.Navigation("DeThis");

                    b.Navigation("Ets");

                    b.Navigation("Tips");
                });

            modelBuilder.Entity("BEARLINGO.Models.Reading", b =>
                {
                    b.Navigation("KetQuaRs");
                });
#pragma warning restore 612, 618
        }
    }
}
